[launcher]
version = 0.0.0+0a19330
description = CIMPlicity AI
author = Will Searle

[id]
version = 0.0.0+0a19330
name = cim-plicity

[install]
build = 1753098090
is_configured = false
state = enabled

[package]
id = cim-plicity
check_for_updates = true

[ui]
label = CIMPlicity AI
supported_themes = light, dark
is_visible = true

[triggers]
reload.cim-plicity_settings = simple
